language: java

jdk:
  - oraclejdk8
  
sudo: false

script: mvn clean verify

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -DskipTests"
  on:
    branch: dev

notifications:
  email:
    on_success: never
    on_failure: change
    
branches:
  only:
    - master
    - dev
    - /^release.*$/
    - /^hotfix.*$/