language: java

jdk:
  - oraclejdk8
  
sudo: false

env:
  global:
    - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

script:
  - mvn clean verify -B

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -DskipTests -B"
  on:
    branch: dev

notifications:
  email:
    on_success: never
    on_failure: change
    
branches:
  only:
    - master
    - dev
    - /^release.*$/
    - /^hotfix.*$/